"""Typed Pydantic models for Gemini API data flow.

These models replace raw ``Dict[str, Any]`` in:
- API payload construction (``generate_content``)
- Tool format conversion
- Response normalization input items
- Structured output format configs

External boundaries (``BaseLLM.call`` signature, ``BaseTool.get_spec``)
remain ``dict`` per the framework contract.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# ======================================================================== #
# Content parts                                                             #
# ======================================================================== #


class InlineData(BaseModel):
    """Binary data embedded inline (images, audio, video, documents)."""

    mime_type: str
    data: str  # base64-encoded


class FileData(BaseModel):
    """Reference to a file via URI (e.g. Google Cloud Storage)."""

    mime_type: str | None = None
    file_uri: str


class FunctionCallPart(BaseModel):
    """A function call generated by the model."""

    name: str
    args: dict[str, Any] = Field(default_factory=dict)
    id: str | None = None


class FunctionResponsePart(BaseModel):
    """A function result sent back to the model."""

    name: str
    response: dict[str, Any]
    id: str | None = None


class GeminiPart(BaseModel):
    """A single content part — exactly one field should be set.

    Gemini's multimodal API uses a parts-based message format where each
    part carries one modality (text, image, function call, etc.).
    """

    text: str | None = None
    inline_data: InlineData | None = None
    file_data: FileData | None = None
    function_call: FunctionCallPart | None = None
    function_response: FunctionResponsePart | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def to_api_dict(self) -> dict[str, Any]:
        """Serialize to the dict format Gemini SDK expects, omitting None fields."""
        return {k: v for k, v in self.model_dump().items() if v is not None}


# ======================================================================== #
# Content (message)                                                         #
# ======================================================================== #


class GeminiRole(str, Enum):
    """Valid role values for Gemini content."""

    USER = "user"
    MODEL = "model"


class GeminiContent(BaseModel):
    """A single message in a Gemini conversation."""

    role: str
    parts: list[GeminiPart]

    def to_api_dict(self) -> dict[str, Any]:
        """Serialize for the Gemini SDK."""
        return {
            "role": self.role,
            "parts": [p.to_api_dict() for p in self.parts],
        }


# ======================================================================== #
# Safety settings                                                           #
# ======================================================================== #


class HarmCategory(str, Enum):
    """Gemini harm categories."""

    HARASSMENT = "HARM_CATEGORY_HARASSMENT"
    HATE_SPEECH = "HARM_CATEGORY_HATE_SPEECH"
    SEXUALLY_EXPLICIT = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    DANGEROUS_CONTENT = "HARM_CATEGORY_DANGEROUS_CONTENT"
    CIVIC_INTEGRITY = "HARM_CATEGORY_CIVIC_INTEGRITY"


class HarmBlockThreshold(str, Enum):
    """Threshold levels for blocking harmful content."""

    BLOCK_NONE = "BLOCK_NONE"
    BLOCK_LOW_AND_ABOVE = "BLOCK_LOW_AND_ABOVE"
    BLOCK_MEDIUM_AND_ABOVE = "BLOCK_MEDIUM_AND_ABOVE"
    BLOCK_ONLY_HIGH = "BLOCK_ONLY_HIGH"
    OFF = "OFF"


class SafetySetting(BaseModel):
    """A single safety setting for content generation."""

    category: str
    threshold: str


# ======================================================================== #
# Generation config                                                         #
# ======================================================================== #


class ThinkingConfig(BaseModel):
    """Configuration for model thinking/reasoning."""

    thinking_budget: int | None = Field(
        None,
        ge=0,
        description="Token budget for model thinking. 0 disables thinking.",
    )


class GenerationConfig(BaseModel):
    """Typed generation config for Gemini API calls."""

    temperature: float | None = None
    top_p: float | None = None
    top_k: int | None = None
    max_output_tokens: int | None = None
    stop_sequences: list[str] | None = None
    candidate_count: int | None = None
    seed: int | None = None
    response_mime_type: str | None = None
    response_json_schema: dict[str, Any] | None = None
    thinking_config: ThinkingConfig | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def to_api_dict(self) -> dict[str, Any]:
        """Serialize for the Gemini SDK, omitting None fields."""
        data: dict[str, Any] = {}
        for k, v in self.model_dump(exclude_none=True).items():
            if v is not None:
                data[k] = v
        return data


# ======================================================================== #
# Generate content payload                                                  #
# ======================================================================== #


class GenerateContentPayload(BaseModel):
    """Typed payload for ``client.models.generate_content()``."""

    model: str
    contents: list[dict[str, Any]]
    config: dict[str, Any] | None = None
    tools: list[dict[str, Any]] | None = None
    system_instruction: str | None = None
    safety_settings: list[dict[str, Any]] | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True)

    @classmethod
    def build(
        cls,
        *,
        model: str,
        contents: list[GeminiContent],
        generation_config: GenerationConfig | None = None,
        tools: list[dict[str, Any]] | None = None,
        system_instruction: str | None = None,
        safety_settings: list[SafetySetting] | None = None,
    ) -> GenerateContentPayload:
        """Construct a payload with proper serialization."""
        serialized_contents = [c.to_api_dict() for c in contents]
        config_dict = generation_config.to_api_dict() if generation_config else None
        safety_dicts = (
            [s.model_dump() for s in safety_settings] if safety_settings else None
        )

        return cls(
            model=model,
            contents=serialized_contents,
            config=config_dict if config_dict else None,
            tools=tools,
            system_instruction=system_instruction,
            safety_settings=safety_dicts,
        )

    def to_api_kwargs(self) -> dict[str, Any]:
        """Serialize to kwargs for ``generate_content()``, dropping ``None`` values."""
        return {
            k: v for k, v in self.model_dump(exclude_none=True).items() if v is not None
        }
