name: Bug Report
description: Report a bug in NucleusIQ
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: input
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      placeholder: nucleusiq, nucleusiq-openai, or both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Run: pip show nucleusiq | grep Version"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code to reproduce the issue.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include the full error traceback if applicable.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      options:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 22.04, macOS 14, Windows 11
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information (logs, screenshots, related issues).
    validations:
      required: false
