name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve NucleusIQ? We'd love to hear it!

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the framework does this relate to?
      options:
        - Agent system (execution modes, orchestration)
        - Prompt engineering
        - Tool system
        - Memory system
        - Plugin system
        - LLM providers (OpenAI, Gemini, etc.)
        - Structured output
        - Documentation
        - Testing / CI
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or what use case does it enable?
      placeholder: "I'm trying to ... but currently ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work? Code examples are welcome.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about.
    validations:
      required: false

  - type: dropdown
    id: willing-to-pr
    attributes:
      label: Would you be willing to submit a PR?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
